dotnet build src
dotnet test src/Core.Abstractions.Tests
dotnet test src/Core.Tests
dotnet test src/Http.Tests
dotnet test src/Session.Abstractions.Tests
dotnet test src/Session.Tests
dotnet test src/Transmission.Abstractions.Tests
dotnet test src/Transmission.Tests
dotnet test src/Transmission.BlobStorage.Tests
dotnet test src/Transmission.EventHub.Tests
